// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/account/data/model/account_model.dart';
import 'features/category/data/model/category_model.dart';
import 'features/transaction/data/model/transaction_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 382033324989994512),
    name: 'AccountModel',
    lastPropertyId: const obx_int.IdUid(9, 4906712001452350410),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5762687634356238683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6642607828898678055),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8962986254979889701),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1136003196780488071),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3594987435910699938),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7263988078248117948),
        name: 'sortOrder',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 3721445483240570850),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1244932568722291277),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6134489207178538838),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2150691393952799244),
        name: 'balance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4906712001452350410),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 9214700060690020303),
    name: 'CategoryModel',
    lastPropertyId: const obx_int.IdUid(9, 7593247305184856939),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5042176435344498329),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4964907963736203626),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 2131731661318091830),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2950322200862300025),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5183834337721085102),
        name: 'sortOrder',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 3028586126921687772),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4652026289613823089),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3128269495404495968),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2927885393013914745),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7816551088761546060),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7593247305184856939),
        name: 'visible',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4887377587349221783),
    name: 'TransactionModel',
    lastPropertyId: const obx_int.IdUid(11, 8236143487117282939),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8265815489559655068),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 240131740609387706),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 3219095287413770953),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 765549453558749912),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2022185303494821467),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3397911784444922825),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6473185591998799718),
        name: 'categoryUuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 1342639113838923788),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7653500323661685717),
        name: 'accountUuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 4503638087803091419),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2423795632474298415),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8872363332800351242),
        name: 'date',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(8, 995482463966676039),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1046574712184831675),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8236143487117282939),
        name: 'toAccountUuid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 4887377587349221783),
    lastIndexId: const obx_int.IdUid(8, 995482463966676039),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AccountModel: obx_int.EntityDefinition<AccountModel>(
      model: _entities[0],
      toOneRelations: (AccountModel object) => [],
      toManyRelations: (AccountModel object) => {},
      getId: (AccountModel object) => object.id,
      setId: (AccountModel object, int id) {
        object.id = id;
      },
      objectToFB: (AccountModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final currencyOffset = fbb.writeString(object.currency);
        final iconCodeOffset = fbb.writeString(object.iconCode);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, currencyOffset);
        fbb.addInt64(4, object.sortOrder);
        fbb.addOffset(5, iconCodeOffset);
        fbb.addInt64(6, object.createdDate.millisecondsSinceEpoch);
        fbb.addFloat64(7, object.balance);
        fbb.addInt64(8, object.colorValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final balanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final colorValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = AccountModel(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          currency: currencyParam,
          balance: balanceParam,
          sortOrder: sortOrderParam,
          iconCode: iconCodeParam,
          createdDate: createdDateParam,
          colorValue: colorValueParam,
        );

        return object;
      },
    ),
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
      model: _entities[1],
      toOneRelations: (CategoryModel object) => [],
      toManyRelations: (CategoryModel object) => {},
      getId: (CategoryModel object) => object.id,
      setId: (CategoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final iconCodeOffset = fbb.writeString(object.iconCode);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.sortOrder);
        fbb.addOffset(4, iconCodeOffset);
        fbb.addInt64(5, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(6, typeOffset);
        fbb.addInt64(7, object.colorValue);
        fbb.addBool(8, object.visible);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final colorValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final visibleParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = CategoryModel(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          sortOrder: sortOrderParam,
          iconCode: iconCodeParam,
          type: typeParam,
          createdDate: createdDateParam,
          colorValue: colorValueParam,
          visible: visibleParam,
        );

        return object;
      },
    ),
    TransactionModel: obx_int.EntityDefinition<TransactionModel>(
      model: _entities[2],
      toOneRelations: (TransactionModel object) => [],
      toManyRelations: (TransactionModel object) => {},
      getId: (TransactionModel object) => object.id,
      setId: (TransactionModel object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final currencyOffset = fbb.writeString(object.currency);
        final typeOffset = fbb.writeString(object.type);
        final categoryUuidOffset = fbb.writeString(object.categoryUuid);
        final accountUuidOffset = fbb.writeString(object.accountUuid);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final toAccountUuidOffset = object.toAccountUuid == null
            ? null
            : fbb.writeString(object.toAccountUuid!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, currencyOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addOffset(5, categoryUuidOffset);
        fbb.addOffset(6, accountUuidOffset);
        fbb.addOffset(7, noteOffset);
        fbb.addInt64(8, object.date.millisecondsSinceEpoch);
        fbb.addInt64(9, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(10, toAccountUuidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final categoryUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final accountUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final toAccountUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = TransactionModel(
          id: idParam,
          uuid: uuidParam,
          amount: amountParam,
          currency: currencyParam,
          type: typeParam,
          categoryUuid: categoryUuidParam,
          accountUuid: accountUuidParam,
          toAccountUuid: toAccountUuidParam,
          note: noteParam,
          date: dateParam,
          createdDate: createdDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AccountModel] entity fields to define ObjectBox queries.
class AccountModel_ {
  /// See [AccountModel.id].
  static final id = obx.QueryIntegerProperty<AccountModel>(
    _entities[0].properties[0],
  );

  /// See [AccountModel.uuid].
  static final uuid = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[1],
  );

  /// See [AccountModel.name].
  static final name = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[2],
  );

  /// See [AccountModel.currency].
  static final currency = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[3],
  );

  /// See [AccountModel.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<AccountModel>(
    _entities[0].properties[4],
  );

  /// See [AccountModel.iconCode].
  static final iconCode = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[5],
  );

  /// See [AccountModel.createdDate].
  static final createdDate = obx.QueryDateProperty<AccountModel>(
    _entities[0].properties[6],
  );

  /// See [AccountModel.balance].
  static final balance = obx.QueryDoubleProperty<AccountModel>(
    _entities[0].properties[7],
  );

  /// See [AccountModel.colorValue].
  static final colorValue = obx.QueryIntegerProperty<AccountModel>(
    _entities[0].properties[8],
  );
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// See [CategoryModel.id].
  static final id = obx.QueryIntegerProperty<CategoryModel>(
    _entities[1].properties[0],
  );

  /// See [CategoryModel.uuid].
  static final uuid = obx.QueryStringProperty<CategoryModel>(
    _entities[1].properties[1],
  );

  /// See [CategoryModel.name].
  static final name = obx.QueryStringProperty<CategoryModel>(
    _entities[1].properties[2],
  );

  /// See [CategoryModel.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<CategoryModel>(
    _entities[1].properties[3],
  );

  /// See [CategoryModel.iconCode].
  static final iconCode = obx.QueryStringProperty<CategoryModel>(
    _entities[1].properties[4],
  );

  /// See [CategoryModel.createdDate].
  static final createdDate = obx.QueryDateProperty<CategoryModel>(
    _entities[1].properties[5],
  );

  /// See [CategoryModel.type].
  static final type = obx.QueryStringProperty<CategoryModel>(
    _entities[1].properties[6],
  );

  /// See [CategoryModel.colorValue].
  static final colorValue = obx.QueryIntegerProperty<CategoryModel>(
    _entities[1].properties[7],
  );

  /// See [CategoryModel.visible].
  static final visible = obx.QueryBooleanProperty<CategoryModel>(
    _entities[1].properties[8],
  );
}

/// [TransactionModel] entity fields to define ObjectBox queries.
class TransactionModel_ {
  /// See [TransactionModel.id].
  static final id = obx.QueryIntegerProperty<TransactionModel>(
    _entities[2].properties[0],
  );

  /// See [TransactionModel.uuid].
  static final uuid = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[1],
  );

  /// See [TransactionModel.amount].
  static final amount = obx.QueryDoubleProperty<TransactionModel>(
    _entities[2].properties[2],
  );

  /// See [TransactionModel.currency].
  static final currency = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[3],
  );

  /// See [TransactionModel.type].
  static final type = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[4],
  );

  /// See [TransactionModel.categoryUuid].
  static final categoryUuid = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[5],
  );

  /// See [TransactionModel.accountUuid].
  static final accountUuid = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[6],
  );

  /// See [TransactionModel.note].
  static final note = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[7],
  );

  /// See [TransactionModel.date].
  static final date = obx.QueryDateProperty<TransactionModel>(
    _entities[2].properties[8],
  );

  /// See [TransactionModel.createdDate].
  static final createdDate = obx.QueryDateProperty<TransactionModel>(
    _entities[2].properties[9],
  );

  /// See [TransactionModel.toAccountUuid].
  static final toAccountUuid = obx.QueryStringProperty<TransactionModel>(
    _entities[2].properties[10],
  );
}
